-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Jan 26, 2023 at 06:40 PM
-- Server version: 8.0.31
-- PHP Version: 7.4.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `db_dien_nuoc_gr`
--

DELIMITER $$
--
-- Procedures
--
CREATE  PROCEDURE `login` (IN `p_email` VARCHAR(150), IN `p_password` VARCHAR(200))   BEGIN
    SELECT * FROM account WHERE email = p_email AND password = p_password;
END$$

DELIMITER ;

-- --------------------------------------------------------

--
-- Table structure for table `account`
--

CREATE TABLE `account` (
  `id_account` int NOT NULL,
  `email` varchar(150) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `PASSWORD` varchar(200) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `fullname` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `avatar` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `account`
--

INSERT INTO `account` (`id_account`, `email`, `PASSWORD`, `fullname`, `avatar`) VALUES
(1, 'nguyenhoangkhangnsc19@gmail.com', 'Abc@123', 'Nguyễn Hoàng Khang', 'avatar.png');

-- --------------------------------------------------------

--
-- Table structure for table `information`
--

CREATE TABLE `information` (
  `id_info` int NOT NULL,
  `linkVideoIntroduce` varchar(200) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `linkFb` varchar(200) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `linkYoutube` varchar(200) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `zalo` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `email` varchar(200) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `address` varchar(250) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `fullname` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `avatar` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `major` varchar(200) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Numberphone` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `information`
--

INSERT INTO `information` (`id_info`, `linkVideoIntroduce`, `linkFb`, `linkYoutube`, `zalo`, `email`, `address`, `fullname`, `avatar`, `major`, `Numberphone`) VALUES
(1, 'https://youtu.be/inpKPQEfIDc', 'https://www.facebook.com/it.nhk.hutech/', 'https://www.youtube.com/channel/UCuotYjXOAo_pthNUV5_SrGg2', '0987546775', 'nguyenhoangkhangnsc19@gmail.com', 'Tổ 40, khu phố Minh An Thị Trấn Minh Lương, Huyện Châu Thành, Tỉnh Kiên Giang. 2', 'Nguyễn Văn Tiến ', 'man.png', 'Kỹ thuật điện2', '0987546775');

-- --------------------------------------------------------

--
-- Table structure for table `post`
--

CREATE TABLE `post` (
  `id_post` int NOT NULL,
  `title` varchar(200) COLLATE utf8mb4_general_ci NOT NULL,
  `content` mediumtext COLLATE utf8mb4_general_ci,
  `timeposted` datetime DEFAULT NULL,
  `views` int DEFAULT NULL,
  `banner` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `keywords` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `tags` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `post`
--

INSERT INTO `post` (`id_post`, `title`, `content`, `timeposted`, `views`, `banner`, `keywords`, `tags`) VALUES
(1, 'Lắp đặt thi công hệ thống nước sạch tại gò quao', 'Service repair electric refers to the maintenance and repair of electrical equipment and systems. This can include anything from small household appliances to large industrial machines. Electric repair services may include troubleshooting and diagnosing problems, replacing faulty parts, and ensuring that the equipment is operating at peak efficiency. Some service repair electric may specialize in certain types of equipment, such as HVAC systems, appliances, or generators.\r\n\r\nService repair electric may also include preventative maintenance, such as regular inspections and cleaning, to help prevent equipment from breaking down and prolong its lifespan. This can help to minimize downtime and reduce the need for costly repairs in the future.\r\n\r\nThe professionals who provide service repair electric are often highly trained and experienced in electrical repair and maintenance. They may be licensed electricians or have specialized training in a particular type of equipment. They use various tools and equipment, such as multimeters, power testers and specialized software to diagnose, troubleshoot and repair the equipment.\r\nOverall, service repair electric is an essential service that helps to ensure that electrical equipment is operating safely and efficiently. It is crucial for both residential and commercial customers, to keep their equipment in good working order and avoid costly breakdowns and repairs.', '2023-01-21 00:00:00', 12, 'banner.png', 'Điện nước Tiến Nguyễn; Sửa chữa điện nước tiến nguyễn; Nguyễn Văn Tiến; Điện nước Tiến Nguyễn', 'Sửa chữa điện; sữa chữa điện gò quao; sữa chữa điện rạch giá; sửa chữa điện nước kiên giang'),
(5, 'Lắp đặt thi công hệ thống nước sạch tại gò quao', 'Service repair electric refers to the maintenance and repair of electrical equipment and systems. This can include anything from small household appliances to large industrial machines. Electric repair services may include troubleshooting and diagnosing problems, replacing faulty parts, and ensuring that the equipment is operating at peak efficiency. Some service repair electric may specialize in certain types of equipment, such as HVAC systems, appliances, or generators.\r\n\r\nService repair electric may also include preventative maintenance, such as regular inspections and cleaning, to help prevent equipment from breaking down and prolong its lifespan. This can help to minimize downtime and reduce the need for costly repairs in the future.\r\n\r\nThe professionals who provide service repair electric are often highly trained and experienced in electrical repair and maintenance. They may be licensed electricians or have specialized training in a particular type of equipment. They use various tools and equipment, such as multimeters, power testers and specialized software to diagnose, troubleshoot and repair the equipment.\r\nOverall, service repair electric is an essential service that helps to ensure that electrical equipment is operating safely and efficiently. It is crucial for both residential and commercial customers, to keep their equipment in good working order and avoid costly breakdowns and repairs.', '2023-01-21 00:00:00', 12, 'banner.png', 'Điện nước Tiến Nguyễn; Sửa chữa điện nước tiến nguyễn; Nguyễn Văn Tiến; Điện nước Tiến Nguyễn', 'Sửa chữa điện; sữa chữa điện gò quao; sữa chữa điện rạch giá; sửa chữa điện nước kiên giang'),
(6, 'Lắp đặt thi công hệ thống nước sạch tại gò quao', 'Service repair electric refers to the maintenance and repair of electrical equipment and systems. This can include anything from small household appliances to large industrial machines. Electric repair services may include troubleshooting and diagnosing problems, replacing faulty parts, and ensuring that the equipment is operating at peak efficiency. Some service repair electric may specialize in certain types of equipment, such as HVAC systems, appliances, or generators.\r\n\r\nService repair electric may also include preventative maintenance, such as regular inspections and cleaning, to help prevent equipment from breaking down and prolong its lifespan. This can help to minimize downtime and reduce the need for costly repairs in the future.\r\n\r\nThe professionals who provide service repair electric are often highly trained and experienced in electrical repair and maintenance. They may be licensed electricians or have specialized training in a particular type of equipment. They use various tools and equipment, such as multimeters, power testers and specialized software to diagnose, troubleshoot and repair the equipment.\r\nOverall, service repair electric is an essential service that helps to ensure that electrical equipment is operating safely and efficiently. It is crucial for both residential and commercial customers, to keep their equipment in good working order and avoid costly breakdowns and repairs.', '2023-01-21 00:00:00', 13, 'banner.png', 'Điện nước Tiến Nguyễn; Sửa chữa điện nước tiến nguyễn; Nguyễn Văn Tiến; Điện nước Tiến Nguyễn', 'Sửa chữa điện; sữa chữa điện gò quao; sữa chữa điện rạch giá; sửa chữa điện nước kiên giang'),
(7, 'Lắp đặt thi công hệ thống nước sạch tại gò quao', 'Service repair electric refers to the maintenance and repair of electrical equipment and systems. This can include anything from small household appliances to large industrial machines. Electric repair services may include troubleshooting and diagnosing problems, replacing faulty parts, and ensuring that the equipment is operating at peak efficiency. Some service repair electric may specialize in certain types of equipment, such as HVAC systems, appliances, or generators.\r\n\r\nService repair electric may also include preventative maintenance, such as regular inspections and cleaning, to help prevent equipment from breaking down and prolong its lifespan. This can help to minimize downtime and reduce the need for costly repairs in the future.\r\n\r\nThe professionals who provide service repair electric are often highly trained and experienced in electrical repair and maintenance. They may be licensed electricians or have specialized training in a particular type of equipment. They use various tools and equipment, such as multimeters, power testers and specialized software to diagnose, troubleshoot and repair the equipment.\r\nOverall, service repair electric is an essential service that helps to ensure that electrical equipment is operating safely and efficiently. It is crucial for both residential and commercial customers, to keep their equipment in good working order and avoid costly breakdowns and repairs.', '2023-01-21 00:00:00', 12, 'banner.png', 'Điện nước Tiến Nguyễn; Sửa chữa điện nước tiến nguyễn; Nguyễn Văn Tiến; Điện nước Tiến Nguyễn', 'Sửa chữa điện; sữa chữa điện gò quao; sữa chữa điện rạch giá; sửa chữa điện nước kiên giang'),
(8, 'Lắp đặt thi công hệ thống nước sạch tại gò quao', 'Service repair electric refers to the maintenance and repair of electrical equipment and systems. This can include anything from small household appliances to large industrial machines. Electric repair services may include troubleshooting and diagnosing problems, replacing faulty parts, and ensuring that the equipment is operating at peak efficiency. Some service repair electric may specialize in certain types of equipment, such as HVAC systems, appliances, or generators.\r\n\r\nService repair electric may also include preventative maintenance, such as regular inspections and cleaning, to help prevent equipment from breaking down and prolong its lifespan. This can help to minimize downtime and reduce the need for costly repairs in the future.\r\n\r\nThe professionals who provide service repair electric are often highly trained and experienced in electrical repair and maintenance. They may be licensed electricians or have specialized training in a particular type of equipment. They use various tools and equipment, such as multimeters, power testers and specialized software to diagnose, troubleshoot and repair the equipment.\r\nOverall, service repair electric is an essential service that helps to ensure that electrical equipment is operating safely and efficiently. It is crucial for both residential and commercial customers, to keep their equipment in good working order and avoid costly breakdowns and repairs.', '2023-01-21 00:00:00', 12, 'banner.png', 'Điện nước Tiến Nguyễn; Sửa chữa điện nước tiến nguyễn; Nguyễn Văn Tiến; Điện nước Tiến Nguyễn', 'Sửa chữa điện; sữa chữa điện gò quao; sữa chữa điện rạch giá; sửa chữa điện nước kiên giang'),
(10, 'Lắp đặt thi công hệ thống nước sạch tại gò quao', 'Service repair electric refers to the maintenance and repair of electrical equipment and systems. This can include anything from small household appliances to large industrial machines. Electric repair services may include troubleshooting and diagnosing problems, replacing faulty parts, and ensuring that the equipment is operating at peak efficiency. Some service repair electric may specialize in certain types of equipment, such as HVAC systems, appliances, or generators.\r\n\r\nService repair electric may also include preventative maintenance, such as regular inspections and cleaning, to help prevent equipment from breaking down and prolong its lifespan. This can help to minimize downtime and reduce the need for costly repairs in the future.\r\n\r\nThe professionals who provide service repair electric are often highly trained and experienced in electrical repair and maintenance. They may be licensed electricians or have specialized training in a particular type of equipment. They use various tools and equipment, such as multimeters, power testers and specialized software to diagnose, troubleshoot and repair the equipment.\r\nOverall, service repair electric is an essential service that helps to ensure that electrical equipment is operating safely and efficiently. It is crucial for both residential and commercial customers, to keep their equipment in good working order and avoid costly breakdowns and repairs.', '2023-01-21 00:00:00', 12, 'banner.png', 'Điện nước Tiến Nguyễn; Sửa chữa điện nước tiến nguyễn; Nguyễn Văn Tiến; Điện nước Tiến Nguyễn', 'Sửa chữa điện; sữa chữa điện gò quao; sữa chữa điện rạch giá; sửa chữa điện nước kiên giang'),
(11, 'Lắp đặt thi công hệ thống nước sạch tại gò quao', 'Service repair electric refers to the maintenance and repair of electrical equipment and systems. This can include anything from small household appliances to large industrial machines. Electric repair services may include troubleshooting and diagnosing problems, replacing faulty parts, and ensuring that the equipment is operating at peak efficiency. Some service repair electric may specialize in certain types of equipment, such as HVAC systems, appliances, or generators.\r\n\r\nService repair electric may also include preventative maintenance, such as regular inspections and cleaning, to help prevent equipment from breaking down and prolong its lifespan. This can help to minimize downtime and reduce the need for costly repairs in the future.\r\n\r\nThe professionals who provide service repair electric are often highly trained and experienced in electrical repair and maintenance. They may be licensed electricians or have specialized training in a particular type of equipment. They use various tools and equipment, such as multimeters, power testers and specialized software to diagnose, troubleshoot and repair the equipment.\r\nOverall, service repair electric is an essential service that helps to ensure that electrical equipment is operating safely and efficiently. It is crucial for both residential and commercial customers, to keep their equipment in good working order and avoid costly breakdowns and repairs.', '2023-01-21 00:00:00', 12, 'banner.png', 'Điện nước Tiến Nguyễn; Sửa chữa điện nước tiến nguyễn; Nguyễn Văn Tiến; Điện nước Tiến Nguyễn', 'Sửa chữa điện; sữa chữa điện gò quao; sữa chữa điện rạch giá; sửa chữa điện nước kiên giang'),
(12, 'Lắp đặt thi công hệ thống nước sạch tại gò quao', 'Service repair electric refers to the maintenance and repair of electrical equipment and systems. This can include anything from small household appliances to large industrial machines. Electric repair services may include troubleshooting and diagnosing problems, replacing faulty parts, and ensuring that the equipment is operating at peak efficiency. Some service repair electric may specialize in certain types of equipment, such as HVAC systems, appliances, or generators.\r\n\r\nService repair electric may also include preventative maintenance, such as regular inspections and cleaning, to help prevent equipment from breaking down and prolong its lifespan. This can help to minimize downtime and reduce the need for costly repairs in the future.\r\n\r\nThe professionals who provide service repair electric are often highly trained and experienced in electrical repair and maintenance. They may be licensed electricians or have specialized training in a particular type of equipment. They use various tools and equipment, such as multimeters, power testers and specialized software to diagnose, troubleshoot and repair the equipment.\r\nOverall, service repair electric is an essential service that helps to ensure that electrical equipment is operating safely and efficiently. It is crucial for both residential and commercial customers, to keep their equipment in good working order and avoid costly breakdowns and repairs.', '2023-01-21 00:00:00', 12, 'banner.png', 'Điện nước Tiến Nguyễn; Sửa chữa điện nước tiến nguyễn; Nguyễn Văn Tiến; Điện nước Tiến Nguyễn', 'Sửa chữa điện; sữa chữa điện gò quao; sữa chữa điện rạch giá; sửa chữa điện nước kiên giang'),
(13, 'Lắp đặt thi công hệ thống nước sạch tại gò quao', 'Service repair electric refers to the maintenance and repair of electrical equipment and systems. This can include anything from small household appliances to large industrial machines. Electric repair services may include troubleshooting and diagnosing problems, replacing faulty parts, and ensuring that the equipment is operating at peak efficiency. Some service repair electric may specialize in certain types of equipment, such as HVAC systems, appliances, or generators.\r\n\r\nService repair electric may also include preventative maintenance, such as regular inspections and cleaning, to help prevent equipment from breaking down and prolong its lifespan. This can help to minimize downtime and reduce the need for costly repairs in the future.\r\n\r\nThe professionals who provide service repair electric are often highly trained and experienced in electrical repair and maintenance. They may be licensed electricians or have specialized training in a particular type of equipment. They use various tools and equipment, such as multimeters, power testers and specialized software to diagnose, troubleshoot and repair the equipment.\r\nOverall, service repair electric is an essential service that helps to ensure that electrical equipment is operating safely and efficiently. It is crucial for both residential and commercial customers, to keep their equipment in good working order and avoid costly breakdowns and repairs.', '2023-01-21 00:00:00', 12, 'banner.png', 'Điện nước Tiến Nguyễn; Sửa chữa điện nước tiến nguyễn; Nguyễn Văn Tiến; Điện nước Tiến Nguyễn', 'Sửa chữa điện; sữa chữa điện gò quao; sữa chữa điện rạch giá; sửa chữa điện nước kiên giang'),
(14, 'Lắp đặt thi công hệ thống nước sạch tại gò quao', 'Service repair electric refers to the maintenance and repair of electrical equipment and systems. This can include anything from small household appliances to large industrial machines. Electric repair services may include troubleshooting and diagnosing problems, replacing faulty parts, and ensuring that the equipment is operating at peak efficiency. Some service repair electric may specialize in certain types of equipment, such as HVAC systems, appliances, or generators.\r\n\r\nService repair electric may also include preventative maintenance, such as regular inspections and cleaning, to help prevent equipment from breaking down and prolong its lifespan. This can help to minimize downtime and reduce the need for costly repairs in the future.\r\n\r\nThe professionals who provide service repair electric are often highly trained and experienced in electrical repair and maintenance. They may be licensed electricians or have specialized training in a particular type of equipment. They use various tools and equipment, such as multimeters, power testers and specialized software to diagnose, troubleshoot and repair the equipment.\r\nOverall, service repair electric is an essential service that helps to ensure that electrical equipment is operating safely and efficiently. It is crucial for both residential and commercial customers, to keep their equipment in good working order and avoid costly breakdowns and repairs.', '2023-01-21 00:00:00', 12, 'banner.png', 'Điện nước Tiến Nguyễn; Sửa chữa điện nước tiến nguyễn; Nguyễn Văn Tiến; Điện nước Tiến Nguyễn', 'Sửa chữa điện; sữa chữa điện gò quao; sữa chữa điện rạch giá; sửa chữa điện nước kiên giang'),
(15, 'Lắp đặt thi công hệ thống nước sạch tại gò quao', 'Service repair electric refers to the maintenance and repair of electrical equipment and systems. This can include anything from small household appliances to large industrial machines. Electric repair services may include troubleshooting and diagnosing problems, replacing faulty parts, and ensuring that the equipment is operating at peak efficiency. Some service repair electric may specialize in certain types of equipment, such as HVAC systems, appliances, or generators.\n\nService repair electric may also include preventative maintenance, such as regular inspections and cleaning, to help prevent equipment from breaking down and prolong its lifespan. This can help to minimize downtime and reduce the need for costly repairs in the future.\n\nThe professionals who provide service repair electric are often highly trained and experienced in electrical repair and maintenance. They may be licensed electricians or have specialized training in a particular type of equipment. They use various tools and equipment, such as multimeters, power testers and specialized software to diagnose, troubleshoot and repair the equipment.\nOverall, service repair electric is an essential service that helps to ensure that electrical equipment is operating safely and efficiently. It is crucial for both residential and commercial customers, to keep their equipment in good working order and avoid costly breakdowns and repairs.', '2023-01-21 00:00:00', 12, 'banner.png', 'Điện nước Tiến Nguyễn; Sửa chữa điện nước tiến nguyễn; Nguyễn Văn Tiến; Điện nước Tiến Nguyễn', 'Sửa chữa điện; sữa chữa điện gò quao; sữa chữa điện rạch giá; sửa chữa điện nước kiên giang'),
(16, 'Lắp đặt hệ thống tưới tiêu tại minh lương', 'Service repair electric refers to the maintenance and repair of electrical equipment and systems. This can include anything from small household appliances to large industrial machines. Electric repair services may include troubleshooting and diagnosing problems, replacing faulty parts, and ensuring that the equipment is operating at peak efficiency. Some service repair electric may specialize in certain types of equipment, such as HVAC systems, appliances, or generators.\r\n\r\nService repair electric may also include preventative maintenance, such as regular inspections and cleaning, to help prevent equipment from breaking down and prolong its lifespan. This can help to minimize downtime and reduce the need for costly repairs in the future.\r\n\r\nThe professionals who provide service repair electric are often highly trained and experienced in electrical repair and maintenance. They may be licensed electricians or have specialized training in a particular type of equipment. They use various tools and equipment, such as multimeters, power testers and specialized software to diagnose, troubleshoot and repair the equipment.\r\nOverall, service repair electric is an essential service that helps to ensure that electrical equipment is operating safely and efficiently. It is crucial for both residential and commercial customers, to keep their equipment in good working order and avoid costly breakdowns and repairs.', '2023-01-23 23:43:03', 100, 'banner.png', 'Điện nước Tiến Nguyễn; Sửa chữa điện nước tiến nguyễn; Nguyễn Văn Tiến; Điện nước Tiến Nguyễn', 'Sửa chữa điện; sữa chữa điện gò quao; sữa chữa điện rạch giá; sửa chữa điện nước kiên giang'),
(17, 'Lắp đặt hệ thống tưới tiêu tại minh lương', 'Service repair electric refers to the maintenance and repair of electrical equipment and systems. This can include anything from small household appliances to large industrial machines. Electric repair services may include troubleshooting and diagnosing problems, replacing faulty parts, and ensuring that the equipment is operating at peak efficiency. Some service repair electric may specialize in certain types of equipment, such as HVAC systems, appliances, or generators.\r\n\r\nService repair electric may also include preventative maintenance, such as regular inspections and cleaning, to help prevent equipment from breaking down and prolong its lifespan. This can help to minimize downtime and reduce the need for costly repairs in the future.\r\n\r\nThe professionals who provide service repair electric are often highly trained and experienced in electrical repair and maintenance. They may be licensed electricians or have specialized training in a particular type of equipment. They use various tools and equipment, such as multimeters, power testers and specialized software to diagnose, troubleshoot and repair the equipment.\r\nOverall, service repair electric is an essential service that helps to ensure that electrical equipment is operating safely and efficiently. It is crucial for both residential and commercial customers, to keep their equipment in good working order and avoid costly breakdowns and repairs.', '2023-01-23 23:43:03', 100, 'banner.png', 'Điện nước Tiến Nguyễn; Sửa chữa điện nước tiến nguyễn; Nguyễn Văn Tiến; Điện nước Tiến Nguyễn', 'Sửa chữa điện; sữa chữa điện gò quao; sữa chữa điện rạch giá; sửa chữa điện nước kiên giang'),
(18, 'Lắp đặt hệ thống tưới tiêu tại minh lương', 'Service repair electric refers to the maintenance and repair of electrical equipment and systems. This can include anything from small household appliances to large industrial machines. Electric repair services may include troubleshooting and diagnosing problems, replacing faulty parts, and ensuring that the equipment is operating at peak efficiency. Some service repair electric may specialize in certain types of equipment, such as HVAC systems, appliances, or generators.\r\n\r\nService repair electric may also include preventative maintenance, such as regular inspections and cleaning, to help prevent equipment from breaking down and prolong its lifespan. This can help to minimize downtime and reduce the need for costly repairs in the future.\r\n\r\nThe professionals who provide service repair electric are often highly trained and experienced in electrical repair and maintenance. They may be licensed electricians or have specialized training in a particular type of equipment. They use various tools and equipment, such as multimeters, power testers and specialized software to diagnose, troubleshoot and repair the equipment.\r\nOverall, service repair electric is an essential service that helps to ensure that electrical equipment is operating safely and efficiently. It is crucial for both residential and commercial customers, to keep their equipment in good working order and avoid costly breakdowns and repairs.', '2023-01-23 23:43:03', 100, 'banner.png', 'Điện nước Tiến Nguyễn; Sửa chữa điện nước tiến nguyễn; Nguyễn Văn Tiến; Điện nước Tiến Nguyễn', 'Sửa chữa điện; sữa chữa điện gò quao; sữa chữa điện rạch giá; sửa chữa điện nước kiên giang'),
(19, 'Lắp đặt hệ thống tưới tiêu tại minh lương', 'Service repair electric refers to the maintenance and repair of electrical equipment and systems. This can include anything from small household appliances to large industrial machines. Electric repair services may include troubleshooting and diagnosing problems, replacing faulty parts, and ensuring that the equipment is operating at peak efficiency. Some service repair electric may specialize in certain types of equipment, such as HVAC systems, appliances, or generators.\r\n\r\nService repair electric may also include preventative maintenance, such as regular inspections and cleaning, to help prevent equipment from breaking down and prolong its lifespan. This can help to minimize downtime and reduce the need for costly repairs in the future.\r\n\r\nThe professionals who provide service repair electric are often highly trained and experienced in electrical repair and maintenance. They may be licensed electricians or have specialized training in a particular type of equipment. They use various tools and equipment, such as multimeters, power testers and specialized software to diagnose, troubleshoot and repair the equipment.\r\nOverall, service repair electric is an essential service that helps to ensure that electrical equipment is operating safely and efficiently. It is crucial for both residential and commercial customers, to keep their equipment in good working order and avoid costly breakdowns and repairs.', '2023-01-23 23:43:03', 100, 'banner.png', 'Điện nước Tiến Nguyễn; Sửa chữa điện nước tiến nguyễn; Nguyễn Văn Tiến; Điện nước Tiến Nguyễn', 'Sửa chữa điện; sữa chữa điện gò quao; sữa chữa điện rạch giá; sửa chữa điện nước kiên giang'),
(20, 'Lắp đặt hệ thống tưới tiêu tại minh lương', 'Service repair electric refers to the maintenance and repair of electrical equipment and systems. This can include anything from small household appliances to large industrial machines. Electric repair services may include troubleshooting and diagnosing problems, replacing faulty parts, and ensuring that the equipment is operating at peak efficiency. Some service repair electric may specialize in certain types of equipment, such as HVAC systems, appliances, or generators.\r\n\r\nService repair electric may also include preventative maintenance, such as regular inspections and cleaning, to help prevent equipment from breaking down and prolong its lifespan. This can help to minimize downtime and reduce the need for costly repairs in the future.\r\n\r\nThe professionals who provide service repair electric are often highly trained and experienced in electrical repair and maintenance. They may be licensed electricians or have specialized training in a particular type of equipment. They use various tools and equipment, such as multimeters, power testers and specialized software to diagnose, troubleshoot and repair the equipment.\r\nOverall, service repair electric is an essential service that helps to ensure that electrical equipment is operating safely and efficiently. It is crucial for both residential and commercial customers, to keep their equipment in good working order and avoid costly breakdowns and repairs.', '2023-01-23 23:43:03', 100, 'banner.png', 'Điện nước Tiến Nguyễn; Sửa chữa điện nước tiến nguyễn; Nguyễn Văn Tiến; Điện nước Tiến Nguyễn', 'Sửa chữa điện; sữa chữa điện gò quao; sữa chữa điện rạch giá; sửa chữa điện nước kiên giang'),
(21, 'Lắp đặt hệ thống tưới tiêu tại minh lương', 'Service repair electric refers to the maintenance and repair of electrical equipment and systems. This can include anything from small household appliances to large industrial machines. Electric repair services may include troubleshooting and diagnosing problems, replacing faulty parts, and ensuring that the equipment is operating at peak efficiency. Some service repair electric may specialize in certain types of equipment, such as HVAC systems, appliances, or generators.\r\n\r\nService repair electric may also include preventative maintenance, such as regular inspections and cleaning, to help prevent equipment from breaking down and prolong its lifespan. This can help to minimize downtime and reduce the need for costly repairs in the future.\r\n\r\nThe professionals who provide service repair electric are often highly trained and experienced in electrical repair and maintenance. They may be licensed electricians or have specialized training in a particular type of equipment. They use various tools and equipment, such as multimeters, power testers and specialized software to diagnose, troubleshoot and repair the equipment.\r\nOverall, service repair electric is an essential service that helps to ensure that electrical equipment is operating safely and efficiently. It is crucial for both residential and commercial customers, to keep their equipment in good working order and avoid costly breakdowns and repairs.', '2023-01-23 23:43:03', 100, 'banner.png', 'Điện nước Tiến Nguyễn; Sửa chữa điện nước tiến nguyễn; Nguyễn Văn Tiến; Điện nước Tiến Nguyễn', 'Sửa chữa điện; sữa chữa điện gò quao; sữa chữa điện rạch giá; sửa chữa điện nước kiên giang'),
(22, 'Lắp đặt hệ thống tưới tiêu tại minh lương', 'Service repair electric refers to the maintenance and repair of electrical equipment and systems. This can include anything from small household appliances to large industrial machines. Electric repair services may include troubleshooting and diagnosing problems, replacing faulty parts, and ensuring that the equipment is operating at peak efficiency. Some service repair electric may specialize in certain types of equipment, such as HVAC systems, appliances, or generators.\r\n\r\nService repair electric may also include preventative maintenance, such as regular inspections and cleaning, to help prevent equipment from breaking down and prolong its lifespan. This can help to minimize downtime and reduce the need for costly repairs in the future.\r\n\r\nThe professionals who provide service repair electric are often highly trained and experienced in electrical repair and maintenance. They may be licensed electricians or have specialized training in a particular type of equipment. They use various tools and equipment, such as multimeters, power testers and specialized software to diagnose, troubleshoot and repair the equipment.\r\nOverall, service repair electric is an essential service that helps to ensure that electrical equipment is operating safely and efficiently. It is crucial for both residential and commercial customers, to keep their equipment in good working order and avoid costly breakdowns and repairs.', '2023-01-23 23:43:03', 100, 'banner.png', 'Điện nước Tiến Nguyễn; Sửa chữa điện nước tiến nguyễn; Nguyễn Văn Tiến; Điện nước Tiến Nguyễn', 'Sửa chữa điện; sữa chữa điện gò quao; sữa chữa điện rạch giá; sửa chữa điện nước kiên giang'),
(23, 'Lắp đặt hệ thống tưới tiêu tại minh lương', 'Service repair electric refers to the maintenance and repair of electrical equipment and systems. This can include anything from small household appliances to large industrial machines. Electric repair services may include troubleshooting and diagnosing problems, replacing faulty parts, and ensuring that the equipment is operating at peak efficiency. Some service repair electric may specialize in certain types of equipment, such as HVAC systems, appliances, or generators.\r\n\r\nService repair electric may also include preventative maintenance, such as regular inspections and cleaning, to help prevent equipment from breaking down and prolong its lifespan. This can help to minimize downtime and reduce the need for costly repairs in the future.\r\n\r\nThe professionals who provide service repair electric are often highly trained and experienced in electrical repair and maintenance. They may be licensed electricians or have specialized training in a particular type of equipment. They use various tools and equipment, such as multimeters, power testers and specialized software to diagnose, troubleshoot and repair the equipment.\r\nOverall, service repair electric is an essential service that helps to ensure that electrical equipment is operating safely and efficiently. It is crucial for both residential and commercial customers, to keep their equipment in good working order and avoid costly breakdowns and repairs.', '2023-01-23 23:43:03', 100, 'banner.png', 'Điện nước Tiến Nguyễn; Sửa chữa điện nước tiến nguyễn; Nguyễn Văn Tiến; Điện nước Tiến Nguyễn', 'Sửa chữa điện; sữa chữa điện gò quao; sữa chữa điện rạch giá; sửa chữa điện nước kiên giang'),
(24, 'Lắp đặt hệ thống tưới tiêu tại minh lương', 'Service repair electric refers to the maintenance and repair of electrical equipment and systems. This can include anything from small household appliances to large industrial machines. Electric repair services may include troubleshooting and diagnosing problems, replacing faulty parts, and ensuring that the equipment is operating at peak efficiency. Some service repair electric may specialize in certain types of equipment, such as HVAC systems, appliances, or generators.\r\n\r\nService repair electric may also include preventative maintenance, such as regular inspections and cleaning, to help prevent equipment from breaking down and prolong its lifespan. This can help to minimize downtime and reduce the need for costly repairs in the future.\r\n\r\nThe professionals who provide service repair electric are often highly trained and experienced in electrical repair and maintenance. They may be licensed electricians or have specialized training in a particular type of equipment. They use various tools and equipment, such as multimeters, power testers and specialized software to diagnose, troubleshoot and repair the equipment.\r\nOverall, service repair electric is an essential service that helps to ensure that electrical equipment is operating safely and efficiently. It is crucial for both residential and commercial customers, to keep their equipment in good working order and avoid costly breakdowns and repairs.', '2023-01-23 23:43:03', 100, 'banner.png', 'Điện nước Tiến Nguyễn; Sửa chữa điện nước tiến nguyễn; Nguyễn Văn Tiến; Điện nước Tiến Nguyễn', 'Sửa chữa điện; sữa chữa điện gò quao; sữa chữa điện rạch giá; sửa chữa điện nước kiên giang'),
(25, 'Lắp đặt hệ thống tưới tiêu tại minh lương', 'Service repair electric refers to the maintenance and repair of electrical equipment and systems. This can include anything from small household appliances to large industrial machines. Electric repair services may include troubleshooting and diagnosing problems, replacing faulty parts, and ensuring that the equipment is operating at peak efficiency. Some service repair electric may specialize in certain types of equipment, such as HVAC systems, appliances, or generators.\r\n\r\nService repair electric may also include preventative maintenance, such as regular inspections and cleaning, to help prevent equipment from breaking down and prolong its lifespan. This can help to minimize downtime and reduce the need for costly repairs in the future.\r\n\r\nThe professionals who provide service repair electric are often highly trained and experienced in electrical repair and maintenance. They may be licensed electricians or have specialized training in a particular type of equipment. They use various tools and equipment, such as multimeters, power testers and specialized software to diagnose, troubleshoot and repair the equipment.\r\nOverall, service repair electric is an essential service that helps to ensure that electrical equipment is operating safely and efficiently. It is crucial for both residential and commercial customers, to keep their equipment in good working order and avoid costly breakdowns and repairs.', '2023-01-23 23:43:03', 100, 'banner.png', 'Điện nước Tiến Nguyễn; Sửa chữa điện nước tiến nguyễn; Nguyễn Văn Tiến; Điện nước Tiến Nguyễn', 'Sửa chữa điện; sữa chữa điện gò quao; sữa chữa điện rạch giá; sửa chữa điện nước kiên giang'),
(26, 'Lắp đặt hệ thống tưới tiêu tại minh lương', 'Service repair electric refers to the maintenance and repair of electrical equipment and systems. This can include anything from small household appliances to large industrial machines. Electric repair services may include troubleshooting and diagnosing problems, replacing faulty parts, and ensuring that the equipment is operating at peak efficiency. Some service repair electric may specialize in certain types of equipment, such as HVAC systems, appliances, or generators.\r\n\r\nService repair electric may also include preventative maintenance, such as regular inspections and cleaning, to help prevent equipment from breaking down and prolong its lifespan. This can help to minimize downtime and reduce the need for costly repairs in the future.\r\n\r\nThe professionals who provide service repair electric are often highly trained and experienced in electrical repair and maintenance. They may be licensed electricians or have specialized training in a particular type of equipment. They use various tools and equipment, such as multimeters, power testers and specialized software to diagnose, troubleshoot and repair the equipment.\r\nOverall, service repair electric is an essential service that helps to ensure that electrical equipment is operating safely and efficiently. It is crucial for both residential and commercial customers, to keep their equipment in good working order and avoid costly breakdowns and repairs.', '2023-01-23 23:43:03', 100, 'banner.png', 'Điện nước Tiến Nguyễn; Sửa chữa điện nước tiến nguyễn; Nguyễn Văn Tiến; Điện nước Tiến Nguyễn', 'Sửa chữa điện; sữa chữa điện gò quao; sữa chữa điện rạch giá; sửa chữa điện nước kiên giang');

-- --------------------------------------------------------

--
-- Table structure for table `product`
--

CREATE TABLE `product` (
  `id_product` int NOT NULL,
  `name` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `description` mediumtext COLLATE utf8mb4_general_ci,
  `imagePath` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `views` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `product`
--

INSERT INTO `product` (`id_product`, `name`, `description`, `imagePath`, `views`) VALUES
(2, 'Công tắc điện 100 W (Bảo hành 1 năm)', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 13),
(3, 'Công tắc điện 200 W (Bảo hành 1 năm)', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 4),
(5, 'Công tắc điện 50 W (Bảo hành 1 năm)', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 99),
(6, 'Công tắc điện 50 W (Bảo hành 1 năm)', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 3),
(7, 'Công tắc điện 50 W (Bảo hành 1 năm)', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 2),
(8, 'Công tắc điện 50 W (Bảo hành 1 năm)', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 2),
(9, 'Công tắc điện 50 W (Bảo hành 1 năm)', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 2),
(10, 'Công tắc điện 50 W (Bảo hành 1 năm)', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 2),
(11, 'Công tắc điện 50 W (Bảo hành 1 năm)', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 2),
(13, 'Công tắc điện 50 W (Bảo hành 1 năm)', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 2),
(14, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 103),
(15, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(16, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(17, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(18, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(19, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(20, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(21, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(22, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(23, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(24, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(25, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(26, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(27, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(28, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(29, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(30, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(31, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(32, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(33, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(34, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(35, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(36, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(37, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(38, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(39, 'Công tắc điện demo', 'Công tắc điện là một thiết bị điều khiển điện năng, chức năng chính của nó là bật tắt hoặc chuyển đổi các thiết bị điện. Công tắc điện có thể sử dụng trong các hệ thống điện như điều khiển đèn, quạt, máy lạnh, máy giặt, máy hút, hệ thống âm thanh và hệ thống điện khác.\r\n\r\nCông tắc điện có nhiều loại với các chức năng khác nhau như công tắc bậ,, công tắc chuyển đổi, công tắc chuyển đổi tự động, công tắc cảm ứng và công tắc điều chỉnh.\r\n\r\nCông tắc bật tiếp đi là loại công tắc được sử dụng để bật tiếp đi các thiết bị điện từ một nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn.\r\n\r\nCông tắc chuyển đổi là loại công tắc được sử dụng để chuyển đổi từ một nguồn điện sang nguồn điện khác, thường được sử dụng trong hệ thống điều khiển đèn hoặc hệ thống điều khiển điện.\r\n\r\nCông tắc chuyển đổi tự động là loại công tắc được sử dụng để tự động chuyển đổi giữa các nguồn điện khác nhau, thường được sử dụng trong hệ thống điều khiển đèn hoặc', 'pathImageDemo.jpg', 100),
(40, 'Công tắc điện - add product', 'Mô tả sản phẩm', 'pathImageDemo.jpg', 0),
(41, 'Hệ thống đèn thông minh', '', 'water-drop.png', 100);

-- --------------------------------------------------------

--
-- Table structure for table `serviceprovide`
--

CREATE TABLE `serviceprovide` (
  `id_service` int NOT NULL,
  `name` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `description` varchar(1000) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `totalProvide` int DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `serviceprovide`
--

INSERT INTO `serviceprovide` (`id_service`, `name`, `description`, `totalProvide`) VALUES
(2, 'Sửa chữa và thay thế các thiết bị điện như cầu chì, cầu bảo vệ, hộp điện', 'Sửa chữa và thay thế các thiết bị điện như cầu chì, cầu bảo vệ, hộp điện', 1000),
(3, 'Sửa chữa và thay thế các thiết bị nước như bồn rửa tay, bồn cầu, van điều khiển nước', 'Sửa chữa và thay thế các thiết bị nước như bồn rửa tay, bồn cầu, van điều khiển nước', 500),
(4, 'Sửa chữa và thay thế các thiết bị nước như bồn rửa tay, bồn cầu, van điều khiển nước', 'Sửa chữa và thay thế các thiết bị nước như bồn rửa tay, bồn cầu, van điều khiển nước', 500),
(5, 'Sửa chữa và thay thế các thiết bị nước như bồn rửa tay, bồn cầu, van điều khiển nước', 'Sửa chữa và thay thế các thiết bị nước như bồn rửa tay, bồn cầu, van điều khiển nước', 500),
(6, 'Sửa chữa và thay thế các thiết bị nước như bồn rửa tay, bồn cầu, van điều khiển nước', 'Sửa chữa và thay thế các thiết bị nước như bồn rửa tay, bồn cầu, van điều khiển nước', 500),
(7, 'Sửa chữa và thay thế các thiết bị nước như bồn rửa tay, bồn cầu, van điều khiển nước', 'Sửa chữa và thay thế các thiết bị nước như bồn rửa tay, bồn cầu, van điều khiển nước', 500),
(8, 'Sửa chữa và thay thế các thiết bị nước như bồn rửa tay, bồn cầu, van điều khiển nước', 'Sửa chữa và thay thế các thiết bị nước như bồn rửa tay, bồn cầu, van điều khiển nước', 500),
(9, 'Sửa chữa và thay thế các thiết bị nước như bồn rửa tay, bồn cầu, van điều khiển nước', 'Sửa chữa và thay thế các thiết bị nước như bồn rửa tay, bồn cầu, van điều khiển nước', 500),
(10, 'Dịch vụ vệ sinh dàn hệ thống nước tự động', '<p>Xin ch&agrave;o&nbsp;</p>\r\n', 100),
(11, 'Dịch vụ vệ sinh dàn hệ thống nước tự động', '<p>Xin ch&agrave;o&nbsp;</p>\r\n', 100);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `account`
--
ALTER TABLE `account`
  ADD PRIMARY KEY (`id_account`);

--
-- Indexes for table `information`
--
ALTER TABLE `information`
  ADD PRIMARY KEY (`id_info`);

--
-- Indexes for table `post`
--
ALTER TABLE `post`
  ADD PRIMARY KEY (`id_post`);

--
-- Indexes for table `product`
--
ALTER TABLE `product`
  ADD PRIMARY KEY (`id_product`);

--
-- Indexes for table `serviceprovide`
--
ALTER TABLE `serviceprovide`
  ADD PRIMARY KEY (`id_service`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `account`
--
ALTER TABLE `account`
  MODIFY `id_account` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `information`
--
ALTER TABLE `information`
  MODIFY `id_info` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `post`
--
ALTER TABLE `post`
  MODIFY `id_post` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=94;

--
-- AUTO_INCREMENT for table `product`
--
ALTER TABLE `product`
  MODIFY `id_product` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=46;

--
-- AUTO_INCREMENT for table `serviceprovide`
--
ALTER TABLE `serviceprovide`
  MODIFY `id_service` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
